// What he can build, each backed by projects that prove it. `proof` holds
// project slugs (linked to their pages); 'site' means this website itself.

export const CAPABILITIES = [
  {
    id: 'web',
    title: 'Full-stack web apps',
    line: 'Production web apps: the data model, the API, accounts and a polished interface on top.',
    icon: 'browser',
    accent: '#0ea5e9',
    span: 2,
    proof: ['deckforge', 'watchmatch', 'cipher', 'site'],
    tech: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'PostgreSQL', 'Prisma', 'NextAuth', 'Flask'],
  },
  {
    id: 'realtime',
    title: 'Real-time & multiplayer',
    line: 'Live systems where many people share one moment: chat rooms, online matches, instant updates.',
    icon: 'bolt',
    accent: '#22c55e',
    span: 1,
    proof: ['gambit', 'cipher'],
    tech: ['Socket.io', 'WebSockets', 'Node.js', 'Eventlet'],
  },
  {
    id: 'motion',
    title: '3D, motion & interaction',
    line: 'Interfaces people enjoy using: 3D scenes, cinematic camera work and smooth, purposeful animation.',
    icon: 'cube',
    accent: '#c4953a',
    span: 1,
    proof: ['gambit', 'watchmatch', 'site'],
    tech: ['Three.js', 'Framer Motion', 'View Transitions'],
  },
  {
    id: 'ai',
    title: 'AI agents & automation',
    line: 'AI that does real work: always-on agents that watch, alert, take action and hold a natural conversation.',
    icon: 'sparkle',
    accent: '#8b5cf6',
    span: 2,
    proof: ['umbros', 'the-five'],
    tech: ['Python', 'Groq', 'MCP', 'FastAPI', 'Discord.py'],
  },
  {
    id: 'ios',
    title: 'Native iOS',
    line: 'Native iPhone apps with home screen widgets, Face ID and on-device data.',
    icon: 'phone',
    accent: '#d97757',
    span: 1,
    proof: ['the-grid'],
    tech: ['Swift', 'SwiftUI', 'SwiftData', 'WidgetKit'],
  },
  {
    id: 'embedded',
    title: 'Embedded & hardware',
    line: 'Firmware for real devices, like a 7-inch touchscreen control panel written in C++.',
    icon: 'chip',
    accent: '#f59e0b',
    span: 1,
    proof: ['the-panel'],
    tech: ['C++', 'ESP32-S3', 'LVGL', 'PlatformIO'],
  },
  {
    id: 'infra',
    title: 'Infrastructure & self-hosting',
    line: 'Linux servers, networking and deployment. Every project on this site is self-hosted.',
    icon: 'server',
    accent: '#dc2626',
    span: 1,
    proof: ['minecraft-server', 'beacon', 'umbros'],
    tech: ['Linux', 'Proxmox', 'nginx', 'Cloudflare', 'systemd', 'PM2'],
  },
];
