// Every project launched, system built, and milestone reached, in order.
export const EVENTS = [
  {
    seq: '01',
    type: 'milestone',
    title: 'Portfolio Conceived',
    description: 'Decided to build a central hub above all individual projects — a permanent home for the full ecosystem as it grows.',
    tag: 'Foundation',
    project: 'Portfolio',
  },
  {
    seq: '02',
    type: 'launch',
    title: 'DeckForge — Initiated',
    description: 'Started building a professional-grade Yu-Gi-Oh! deck builder and hand simulator. Established the landing page, auth flows, and core architecture.',
    tag: 'DeckForge',
    project: 'DeckForge',
  },
  {
    seq: '03',
    type: 'launch',
    title: 'DeckForge — Deck Builder Live',
    description: 'Shipped the core deck builder interface: full 13,000+ card database, search with filters, deck management, two-column layout, and a click-to-pin card preview panel.',
    tag: 'DeckForge',
    project: 'DeckForge',
  },
  {
    seq: '04',
    type: 'launch',
    title: 'Cipher — Built & Shipped',
    description: 'Built an ephemeral chat platform from scratch. Flask + SocketIO backend, in-memory rooms, zero persistence, zero accounts. Private by design.',
    tag: 'Cipher',
    project: 'Cipher',
  },
  {
    seq: '05',
    type: 'launch',
    title: 'WatchMatch — Built & Shipped',
    description: 'Built a personalised watch recommendation engine. Quiz flow, swipe mode, and a curated database of 100+ watches matched by lifestyle, budget, wrist size, and style.',
    tag: 'WatchMatch',
    project: 'WatchMatch',
  },
  {
    seq: '06',
    type: 'milestone',
    title: 'Portfolio v1.0 — Live',
    description: 'Portfolio launched at daniyalzia.co.uk. All three projects showcased. The ecosystem is now publicly visible.',
    tag: 'Portfolio',
    project: 'Portfolio',
  },
  {
    seq: '07',
    type: 'launch',
    title: 'Home Server — Self-Hosted',
    description: 'Set up a home server to host every project, with networking, routing and uptime handled in-house instead of a cloud provider.',
    tag: 'Infrastructure',
    project: 'Infra',
  },
  {
    seq: '08',
    type: 'launch',
    title: 'Full Ecosystem Live',
    description: 'DeckForge, Cipher, WatchMatch, and the portfolio are all publicly accessible under daniyalzia.co.uk. Project links active across the portfolio.',
    tag: 'Ecosystem',
    project: 'All',
  },
  {
    seq: '09',
    type: 'launch',
    title: 'The Five — Five-Agent AI Platform',
    description: 'Grew a single private AI into five distinct Discord companions, each scoped to one part of everyday life — calendar and email, trip planning, casual chat, food tracking, and more.',
    tag: 'The Five',
    project: 'TheFive',
  },
  {
    seq: '10',
    type: 'launch',
    title: 'Gambit — Built & Shipped',
    description: 'Shipped a full 3D medieval chess experience — AI opponents at three difficulty tiers, real-time private multiplayer with room codes, cinematic capture animations, and a ranked match system with replays.',
    tag: 'Gambit',
    project: 'Gambit',
  },
  {
    seq: '11',
    type: 'launch',
    title: 'Minecraft Server — Launched',
    description: 'Turned a personal singleplayer world into a real 24/7 Minecraft server for a small group of friends — proper whitelist, real accounts, automatic backups.',
    tag: 'Minecraft Server',
    project: 'MinecraftServer',
  },
  {
    seq: '12',
    type: 'launch',
    title: 'Umbros — Homelab Guardian, Live',
    description: 'Built an always-on AI that watches over the home server and speaks up unprompted in Discord — infra health, security monitoring, live Minecraft admin, and presence detection, all from one voice that never needs to be asked.',
    tag: 'Umbros',
    project: 'Umbros',
  },
  {
    seq: '13',
    type: 'launch',
    title: 'Beacon — Minecraft Admin Dashboard',
    description: 'Shipped a private admin dashboard for the Minecraft server — live console, whitelist management, and a full inventory viewer rendering real armor, enchantments, and trims.',
    tag: 'Beacon',
    project: 'Beacon',
  },
  {
    seq: '14',
    type: 'launch',
    title: 'The Grid — iOS App, Feature-Complete',
    description: 'Built a native iOS app for freeform notes and a daily dashboard — boards, a Today view with calendar and mail, Face ID lock, and a home screen widget.',
    tag: 'The Grid',
    project: 'TheGrid',
  },
  {
    seq: '15',
    type: 'launch',
    title: 'The Panel — Physical Wall Panel, Live',
    description: 'Wrote and deployed custom firmware for a 7-inch touchscreen mounted on the office wall — live status tiles for the home server, PC control, TV control, and more.',
    tag: 'The Panel',
    project: 'ThePanel',
  },
  {
    seq: '16',
    type: 'launch',
    title: 'Cipher — Major Overhaul',
    description: 'Rebuilt Cipher around end-to-end encryption: messages and names are encrypted in the browser before they\'re sent, the key exists only in the invite link, and the server stores nothing. Added a burn button, room locking, and a panic key.',
    tag: 'Cipher',
    project: 'Cipher',
  },
];

export const PROJECT_COLORS = {
  DeckForge: '#d97706',
  Cipher:    '#6b7280',
  WatchMatch:'#0ea5e9',
  Portfolio: '#dc2626',
  Infra:     '#3b82f6',
  All:       '#22c55e',
  TheFive: '#8b5cf6',
  Gambit:    '#c4953a',
  MinecraftServer: '#65a30d',
  Umbros:    '#e11d48',
  Beacon:    '#0891b2',
  ThePanel: '#f59e0b',
  TheGrid:   '#d97757',
};
